#
# This source file is part of the StanfordBDHG Template Application project
#
# SPDX-FileCopyrightText: 2023 Stanford University
#
# SPDX-License-Identifier: MIT
#

name: Build and Test

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  reuse_action:
    name: REUSE Compliance Check
    uses: StanfordBDHG/.github/.github/workflows/reuse.yml@v2
  swiftlint:
    name: SwiftLint
    uses: StanfordBDHG/.github/.github/workflows/swiftlint.yml@v2
  ios:
    name: Build and Test iOS
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      scheme: TemplateApplication
      artifactname: TemplateApplication.xcresult
  ipados:
    name: Build and Test iPadOS
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      scheme: TemplateApplication
      resultBundle: TemplateApplicationiPadOS.xcresult
      destination: 'platform=iOS Simulator,name=iPad mini (6th generation)'
      artifactname: TemplateApplicationiPadOS.xcresult
  visionos:
    name: Build and Test visionOS
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      xcodeversion: latest
      scheme: TemplateApplication
      destination: 'platform=visionOS Simulator,name=Apple Vision Pro'
      test: false
  uploadcoveragereport:
    name: Upload Coverage Report
    needs: [ios, ipados]
    uses: StanfordBDHG/.github/.github/workflows/create-and-upload-coverage-report.yml@v2
    with:
      coveragereports: TemplateApplication.xcresult TemplateApplicationiPadOS.xcresult
